# Generated by Django 4.0.4 on 2022-06-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_client_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='money',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=12),
            preserve_default=False,
        ),
    ]
