# Generated by Django 4.0.4 on 2022-06-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='incompleteorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='completeorder',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.order'),
        ),
        migrations.AlterField(
            model_name='incompleteorder',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.order'),
        ),
        migrations.AlterField(
            model_name='incompleteorder',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'CANCELLED')], max_length=1),
        ),
    ]
