# Generated by Django 4.0.4 on 2022-06-23 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_completeorder_id_remove_incompleteorder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeorder',
            name='price_per_stock',
        ),
        migrations.AddField(
            model_name='order',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 15, 38, 15, 889090)),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incompleteorder',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Cancelled')], max_length=1),
        ),
    ]
