# Generated by Django 4.0.4 on 2022-06-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_company_lastest_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='acronym',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
