# Generated by Django 4.0.4 on 2022-06-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_company_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_type',
            field=models.CharField(choices=[('BM', 'Buy Market'), ('BL', 'Buy Limit'), ('BS', 'Buy Stop'), ('SM', 'Sell Market'), ('SL', 'Sell Limit'), ('SS', 'Sell Stop')], max_length=2),
        ),
    ]
